### ISSUE TITLE
Randomize world creation and create occupancy grid maps

### ISSUE THREAD

**Issue by DharminB** [b-it-bots/mas_industrial_robotics#136]
Generate world configuration for at work scenario (walls and workstations and shelves)
This will be represented using a `.xacro` file.
Accompanied with it should be an occupancy grid (`.pgm` and `.yaml`) (along with `navigation_goals.yaml` if possible)

This could help the testing of robocup related software since we can test against different configurations of workstations in simulation.

**Comment by Sushant-Chavan** [comment]
@DharminB Since there is no description I am not sure what this issue is exactly about, however, you may find [this](https://github.com/LIKERobo/SemanticMapGeneration) repository helpful as it deals with generating random occupancy grid maps. You can find more details on how it is done in [this paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8968111). Specifically `Section VI` of the paper.
