### ISSUE TITLE
[PDDL] setting priority for staging objects 

### ISSUE THREAD

**Issue by kvnptl** [b-it-bots/mas_industrial_robotics#286]
Based on the object dimension, stage the object on a specified location.

**Comment by kvnptl** [comment]
Is it tested? Working? update status?

**Comment by MannavaVivek** [comment]
The planning aspect of this issue is done. Plan will now be generated to accommodate larger objects in PLATFORM_RIGHT. It still needs to be tested rigorously with the refbox and the actual objects, as the current testing was only done as proof of working with miscellaneous objects marked as large in the pddl.
